### ISSUE TITLE
continueStory 的问题

### ISSUE THREAD

**Issue by VecHK** [NT3Games/TraceWindGame#8]
@gledos 

https://github.com/NT3Games/TraceWindGame/blob/812ad99411832de3da3277930176c74a599e14fb/main.js#L76

continueStory 好像不是构造函数？这样写，就相当于 `'audio' in window` 了

**Comment by gledos** [comment]
😂 不知道…… main.js 里面的内容都是官方的，我没有修改过。

（前文已修改，刚才输入错了……导致意思完全相反……）

**Comment by yahvk-cuna** [comment]
放到 window 里也没什么大问题吧

**Comment by VecHK** [comment]
> 放到 window 里也没什么大问题吧

确实。但这种从代码健壮性角度上来看，泄露变量并不是什么好事。
